#################
#### MONITORS ###
#################

source = ~/.config/hypr/configs/monitors.conf

####################
#### MY PROGRAMS ###
####################

source = ~/.config/hypr/configs/programs.conf

##################
#### AUTOSTART ###
##################

source = ~/.config/hypr/configs/autostart.conf

##############################
#### ENVIRONMENT VARIABLES ###
##############################

source = ~/.config/hypr/configs/environment_variables.conf

######################
#### LOOK AND FEEL ###
######################

source = ~/.config/hypr/configs/look_and_feel.conf

##############################
####      ANIMATIONS      ####
##############################

source = ~/.config/hypr/configs/animations.conf
##############
#### INPUT ###
#############

source = ~/.config/hypr/configs/input.conf

####################
#### KEYBINDINGS ###
####################


source = ~/.config/hypr/configs/keybindings.conf


##############################
### WINDOWS AND WORKSPACES ###
##############################



source = ~/.config/hypr/configs/windowrule.conf
source = ~/.config/hypr/configs/layerrule.conf


#################################
#########    plugins    #########
#################################

source = ~/.config/hypr/configs/plugins.conf



