
#  ▄▄▄       █    ██ ▄▄▄█████▓ ▒█████    ██████ ▄▄▄█████▓ ▄▄▄       ██▀███  ▄▄▄█████▓
# ▒████▄     ██  ▓██▒▓  ██▒ ▓▒▒██▒  ██▒▒██    ▒ ▓  ██▒ ▓▒▒████▄    ▓██ ▒ ██▒▓  ██▒ ▓▒
# ▒██  ▀█▄  ▓██  ▒██░▒ ▓██░ ▒░▒██░  ██▒░ ▓██▄   ▒ ▓██░ ▒░▒██  ▀█▄  ▓██ ░▄█ ▒▒ ▓██░ ▒░
# ░██▄▄▄▄██ ▓▓█  ░██░░ ▓██▓ ░ ▒██   ██░  ▒   ██▒░ ▓██▓ ░ ░██▄▄▄▄██ ▒██▀▀█▄  ░ ▓██▓ ░ 
#  ▓█   ▓██▒▒▒█████▓   ▒██▒ ░ ░ ████▓▒░▒██████▒▒  ▒██▒ ░  ▓█   ▓██▒░██▓ ▒██▒  ▒██▒ ░ 
#  ▒▒   ▓▒█░░▒▓▒ ▒ ▒   ▒ ░░   ░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░  ▒ ░░    ▒▒   ▓▒█░░ ▒▓ ░▒▓░  ▒ ░░   
#   ▒   ▒▒ ░░░▒░ ░ ░     ░      ░ ▒ ▒░ ░ ░▒  ░ ░    ░      ▒   ▒▒ ░  ░▒ ░ ▒░    ░    
#   ░   ▒    ░░░ ░ ░   ░      ░ ░ ░ ▒  ░  ░  ░    ░        ░   ▒     ░░   ░   ░      
#       ░  ░   ░                  ░ ░        ░                 ░  ░   ░              

exec-once = hyprpm reload -n
exec-once = $terminal
## exec-once = nm-applet &
exec-once = waybar & firefox & dunst &  hyprpaper 
exec-once = discord
exec-once = hypridle
# exec-once = slack
exec-once = hyprsunset
exec-once = spotify


exec-once = hyprctl setcursor Bibata-Modern-Ice 20
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec-once = gsettings set org.gnome.desktop.interface cursor-size 20

exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-dracula'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

exec-once = gsettings set org.gnome.desktop.interface font-name 'Cantarell 10'
exec-once = gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 10'
exec-once = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'
exec-once = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec-once = gsettings set org.gnome.desktop.interface font-hinting 'full'



