


#  ██▓    ▄▄▄     ▓██   ██▓▓█████  ██▀███   ██▀███   █    ██  ██▓    ▓█████ 
# ▓██▒   ▒████▄    ▒██  ██▒▓█   ▀ ▓██ ▒ ██▒▓██ ▒ ██▒ ██  ▓██▒▓██▒    ▓█   ▀ 
# ▒██░   ▒██  ▀█▄   ▒██ ██░▒███   ▓██ ░▄█ ▒▓██ ░▄█ ▒▓██  ▒██░▒██░    ▒███   
# ▒██░   ░██▄▄▄▄██  ░ ▐██▓░▒▓█  ▄ ▒██▀▀█▄  ▒██▀▀█▄  ▓▓█  ░██░▒██░    ▒▓█  ▄ 
# ░██████▒▓█   ▓██▒ ░ ██▒▓░░▒████▒░██▓ ▒██▒░██▓ ▒██▒▒▒█████▓ ░██████▒░▒████▒
# ░ ▒░▓  ░▒▒   ▓▒█░  ██▒▒▒ ░░ ▒░ ░░ ▒▓ ░▒▓░░ ▒▓ ░▒▓░░▒▓▒ ▒ ▒ ░ ▒░▓  ░░░ ▒░ ░
# ░ ░ ▒  ░ ▒   ▒▒ ░▓██ ░▒░  ░ ░  ░  ░▒ ░ ▒░  ░▒ ░ ▒░░░▒░ ░ ░ ░ ░ ▒  ░ ░ ░  ░
#   ░ ░    ░   ▒   ▒ ▒ ░░     ░     ░░   ░   ░░   ░  ░░░ ░ ░   ░ ░      ░   
#     ░  ░     ░  ░░ ░        ░  ░   ░        ░        ░         ░  ░   ░  ░
#                  ░ ░                                                      




layerrule = blur on, match:namespace test
layerrule = ignore_alpha 0, match:namespace test
layerrule = no_anim on, match:namespace test

layerrule = blur on, match:namespace wofi
layerrule = ignore_alpha 0, match:namespace wofi
layerrule = no_anim on, match:namespace ^(selection)$

layerrule = blur on, match:namespace termspawner
layerrule = ignore_alpha 0, match:namespace termspawner
layerrule = no_anim on, match:namespace termspawner

layerrule = animation fade, match:namespace shell:background


layerrule = blur on, match:namespace shell:bar
layerrule = blur_popups on, match:namespace shell:bar
layerrule = ignore_alpha 0, match:namespace shell:bar
layerrule = blur on, match:namespace shell:notifications
layerrule = ignore_alpha 0, match:namespace shell:notifications
layerrule = no_anim on, match:namespace shell:notifications

layerrule = no_anim on, match:namespace shell:screenshot

layerrule = blur on, match:namespace shell:launcher
layerrule = ignore_alpha 0, match:namespace shell:launcher
layerrule = animation popin 90%, match:namespace shell:launcher

# See https://wiki.hyprland.org/Configuring/Window-Rules/

layerrule = blur on,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi
layerrule = blur on ,match:namespace otifications
layerrule = ignore_alpha 0,match:namespace notifications
layerrule = blur on,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window
layerrule = blur on,match:namespace swaync-control-center
layerrule = ignore_alpha 0,match:namespace swaync-control-center
layerrule = blur on,match:namespace logout_dialog
layerrule = blur on, match:namespace dunst
layerrule = ignore_alpha 0.3, match:namespace dunst


layerrule = blur on
